### ISSUE TITLE
unexpected error

### ISSUE THREAD

**Issue by pvdhelm1974** [cpolhout/loqed_custom_component#9]
Since the last HA update I can't connect to my loqed lock.
I get an unexpected error and tried to remove the integration from HA. This does't help.  

what can we do about it

`Logger: homeassistant
Source: custom_components/loqed/config_flow.py:89 
Integration: LOQED Touch Smart Lock 
First occurred: 14:44:58 (1 occurrences) 
Last logged: 14:44:58

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/discovery_flow.py", line 74, in _async_process_pending_flows
    await gather_with_concurrency(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 199, in gather_with_concurrency
    return await gather(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 197, in sem_task
    return await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 205, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 232, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 335, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/loqed/config_flow.py", line 89, in async_step_zeroconf
    lock_data = await api.async_get_lock_details()
  File "/usr/local/lib/python3.9/site-packages/loqedAPI/loqed.py", line 237, in async_get_lock_details
    resp = await self.apiclient.request("get", "status")
  File "/usr/local/lib/python3.9/site-packages/loqedAPI/loqed.py", line 35, in request
    return await self.websession.request(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected`

tnx

**Comment by pvdhelm1974** [comment]
still get the error and no answer
